FROM tensorflow/tensorflow:1.5.1-py3
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    PIP_INSTALL="python -m pip --no-cache-dir install --upgrade" && \
    apt-get update && \
    



# ==================================================================
# keras
# ------------------------------------------------------------------

    $PIP_INSTALL \
        h5py \
        keras \
        && \

# ==================================================================
# tensorlayer
# ------------------------------------------------------------------

    $PIP_INSTALL  tensorlayer && \
   
# ==================================================================
# tflearn
# ------------------------------------------------------------------

    $PIP_INSTALL  tflearn  && \
    

# ==================================================================

# config & cleanup
# ------------------------------------------------------------------
    
    mkdir -p /root/.keras/datasets  && \
    cd  /root/.keras/datasets  && \
    curl -O https://s3.amazonaws.com/img-datasets/mnist.npz
    
    WORKDIR "/root"
    CMD ["/bin/bash"]
